name: pr

on:
  pull_request:

jobs:
  check-commits:
    uses: wittdennis/pipelines/.github/workflows/cog-validate.yaml@749bb65f519a91aab3502c33024e62051793edda # 2.0.46
    with:
      check-latest-tag-only: true

  ansible-lint:
    uses: wittdennis/pipelines/.github/workflows/ansible-lint.yaml@749bb65f519a91aab3502c33024e62051793edda # 2.0.46
    with:
      requirements-file: requirements.yml

  ansible-test:
    uses: wittdennis/pipelines/.github/workflows/ansible-test.yaml@749bb65f519a91aab3502c33024e62051793edda # 2.0.46
